=== PabloFdez06/Prueba_LGDM_Propiedades/propiedades.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="propiedades">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="propiedad" type="PropiedadType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="PropiedadType">
        <xs:sequence>
            <xs:element name="precioAlquiler" type="xs:int"/>
            <xs:element name="localizacion" type="LocalizacionType"/>
            <xs:element name="metrosCuadrados" type="xs:int"/>
            <xs:element name="anioConstruccion" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="LocalizacionType">
        <xs:sequence>
            <xs:element name="localidad" type="xs:string"/>
            <xs:element name="calle" type="xs:string"/>
            <xs:element name="codigoPostal" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>


</xs:schema>

=== PabloFdez06/Prueba_LGDM_Propiedades/propiedades.xml
<propiedades xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="propiedades.xsd">

    <propiedad>
        <precioAlquiler>250000</precioAlquiler>

        <localizacion>
            <localidad>Cadiz</localidad>
            <calle>Calle 1</calle>
            <codigoPostal>1</codigoPostal>
        </localizacion>

        <metrosCuadrados>80</metrosCuadrados>
        <anioConstruccion>2019</anioConstruccion>

    </propiedad>

    <propiedad>
        <precioAlquiler>128000</precioAlquiler>

        <localizacion>
            <localidad>Sevilla</localidad>
            <calle>Calle 2</calle>
            <codigoPostal>2</codigoPostal>
        </localizacion>

        <metrosCuadrados>64</metrosCuadrados>
        <anioConstruccion>1999</anioConstruccion>

    </propiedad>

    <propiedad>
        <precioAlquiler>203000</precioAlquiler>

        <localizacion>
            <localidad>Albacete</localidad>
            <calle>Calle 3</calle>
            <codigoPostal>3</codigoPostal>
        </localizacion>

        <metrosCuadrados>75</metrosCuadrados>
        <anioConstruccion>2015</anioConstruccion>

    </propiedad>

</propiedades>
